version: "1.0"
services:
  postgres:
    image: postgres:9.6
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    container-name: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"

  mongo:
    image: mongo:4.4.5
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: pools
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init.js

  airflow:
    build: './airflow'
    restart: always
    depends_on:
      - postgres
      - mongo
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build: .
      container_name: app
    ports:
      - 8081:8081
    depends_on:
      - airflow
    environment:
      profile: prod
